stages:
  - build
  - push
  - deploy

build-job:
  stage: build
  script:
    - echo "Start build"
    - docker build -t sssi56/nginx-registry:latest .
    - echo "Finish build"

push-job:
  stage: push
  script:
    - echo "Start push"
    - docker login -u "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD"
    - docker push sssi56/nginx-registry:latest
    - echo "Finish push"

deploy-job:
  stage: deploy
  script:
    - echo "Start deploy"
    - docker stop nginx-registry
    - docker rm nginx-registry
    - docker-compose up -d
    - echo "Finish deploy"